<<<<<<< HEAD
<<<<<<< HEAD
version: '3'
services:
  react-app:
    build: .
    ports:
      - "80:80"
=======
=======
>>>>>>> c55fed3a34a6c63beaec023dca49b953b518bb87
version: "3"
services:
  app:
    build: .
    ports:
      - "80:80"

<<<<<<< HEAD
>>>>>>> c55fed3a34a6c63beaec023dca49b953b518bb87
=======
>>>>>>> c55fed3a34a6c63beaec023dca49b953b518bb87
