name: Build and Push Docker Image

on:
  push:
    branches: [ dev, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and push
      run: |
        if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
          docker build -t dharsh177/devops-pub:latest .
          docker push dharsh177/devops-pub:latest
        elif [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
          docker build -t dharsh177/devops-pri:latest .
          docker push dharsh177/devops-pri:latest
        fi
